apiVersion: v1
kind: Service
metadata:
  name: <APP_NAME>-service
  namespace: "<NAMESPACE>"
spec:
  selector:
    app: <APP_NAME>
  ports:
    - protocol: TCP
      port: <APP_PORT>
      targetPort: <APP_PORT>
  type: ClusterIP


